#!/bin/bash

talos_dir="$(dirname -- "$0")"
build_talos_image_dir="$(dirname -- "${talos_dir}")"

. "${build_talos_image_dir}/buildenv.sh"

cd "${talos_dir}"

set -e

renice -n 19 $$

rm -Rf build
git clone ${TALOS_GIT_FLAGS} --branch "${TALOSRELEASE}" "https://github.com/${TALOS_GITHUB}" build

cp -v *.patch build

cd build

git apply custom_uboot_and_kernel.patch
#git apply remove_boost_add_stable_corefreq.patch

make -j$(nproc) clean

#make uki-certs
make -j$(nproc) kernel initramfs PLATFORM=linux/arm64
make -j$(nproc) installer IMAGE_REGISTRY="${REGISTRY}" PLATFORM=linux/arm64 PUSH=true
make -j$(nproc) imager IMAGE_REGISTRY="${REGISTRY}" PLATFORM=linux/arm64 PUSH=true
make -j$(nproc) iso IMAGE_REGISTRY="${REGISTRY}" PLATFORM=linux/arm64 PUSH=true 
make -j$(nproc) sbc-rpi_generic IMAGE_REGISTRY="${REGISTRY}" PLATFORM=linux/arm64 PUSH=true

echo 'clean /dev/sda with:'
echo 
echo 'sudo wipefs -a /dev/sda ; sync'
echo
echo
echo 'write image with:'
echo
echo 'time xz -d < _out/metal-rpi_generic-arm64.raw.xz | sudo dd of=/dev/sda bs=1M status=progress conv=fsync ; sync'
echo

cd "${build_talos_image_dir}"
